# PyTorch Tutorial

KAIST, October 2018

By Dongkyum Kim

Ref. Sandeep Subramanian, MILA, November 2017

## Introduction to the torch tensor library
### Torch's numpy equivalent with GPU support

In [2]:
from __future__ import print_function
import numpy as np
import torch

### Initialize a random tensor with shape

A tensor filled with random numbers from a normal distribution
with mean `0` and variance `1`

In [3]:
torch.randn(4, 4)

tensor([[ 0.1680,  0.1251,  0.5554,  0.3480],
        [-0.7482,  0.5483,  1.3612,  1.2223],
        [ 0.1833, -1.2773, -1.6825,  0.5582],
        [ 0.2090,  0.8240, -1.9599,  1.5998]])

In [4]:
np.random.randn(4, 4)

array([[ 0.7133378 , -1.53162935, -1.05142611, -0.28741783],
       [-0.0371589 ,  0.00374062, -0.00822873,  1.65399837],
       [-0.60751848, -0.39953287, -0.92695193,  1.41517738],
       [ 0.65135586, -0.31883655,  0.19100358,  2.06445106]])

### Initialize a tensor with list / numpy object

In [5]:
torch.tensor(range(10))

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
torch.tensor(np.arange(1,10))

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=torch.int32)

### Shape of tensor

![](https://www.oreilly.com/library/view/elegant-scipy/9781491922927/assets/elsp_0105.png)

In [7]:
x = torch.randn(4)
print(x)
print(x.shape)

tensor([ 1.3068,  1.1371, -0.7975, -0.0732])
torch.Size([4])


In [8]:
x = torch.randn(2, 3)
print(x)
print(x.shape)

tensor([[ 1.0219, -1.4718, -1.3264],
        [ 0.2943, -1.0765,  0.5840]])
torch.Size([2, 3])


In [9]:
x = torch.randn(4, 3, 2)
print(x)
print(x.shape)

tensor([[[-0.4419,  0.2811],
         [ 0.9264,  0.7388],
         [-0.1364, -1.4341]],

        [[-0.8020,  1.0708],
         [-1.5296, -0.7760],
         [ 0.9968,  0.5660]],

        [[-0.6585,  0.5405],
         [-0.6415,  0.6770],
         [ 0.8458, -0.3436]],

        [[ 0.2163,  0.0183],
         [ 1.0402,  1.7349],
         [-1.9247, -0.7873]]])
torch.Size([4, 3, 2])


### Frequently used methods defined in a tensor

- `mean` : mean
- `std` : standard deviation
- `sqrt` : square root

In [10]:
x = torch.arange(1, 10).float()
print(x)
print('mean of x :', x.mean())
print('standard deviation of x :', x.std())
print('square root of x :', x.sqrt())

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])
mean of x : tensor(5.)
standard deviation of x : tensor(2.7386)
square root of x : tensor([1.0000, 1.4142, 1.7321, 2.0000, 2.2361, 2.4495, 2.6458, 2.8284, 3.0000])


In [11]:
x = np.arange(1, 10)
print(x)
print('mean of x :', x.mean())
print('standard deviation of x :', x.std())
print('square root of x :', np.sqrt(x))

[1 2 3 4 5 6 7 8 9]
mean of x : 5.0
standard deviation of x : 2.581988897471611
square root of x : [1.         1.41421356 1.73205081 2.         2.23606798 2.44948974
 2.64575131 2.82842712 3.        ]


### Compute mean along to axis

In [13]:
x = np.random.randn(2, 3)

print(x.mean(axis=0))
print(x.mean(axis=1))

[ 1.24659574 -0.72536545 -0.1295955 ]
[ 0.46815917 -0.20706931]


In [14]:
x = torch.tensor(x)

print(x.mean(dim=0))
print(x.mean(dim=1))

tensor([ 1.2466, -0.7254, -0.1296], dtype=torch.float64)
tensor([ 0.4682, -0.2071], dtype=torch.float64)


### Tensor Types
source: http://pytorch.org/docs/master/tensors.html

Data type | dtype | CPU tensor | GPU tensor
----------|-------|------------|-----------
32-bit floating point | torch.float32 or torch.float | torch.FloatTensor | torch.cuda.FloatTensor
64-bit floating point | torch.float64 or torch.double | torch.DoubleTensor | torch.cuda.DoubleTensor
16-bit floating point | torch.float16 or torch.half | torch.HalfTensor | torch.cuda.HalfTensor
8-bit integer (unsigned) | torch.uint8 | torch.ByteTensor | torch.cuda.ByteTensor
8-bit integer (signed) | torch.int8 | torch.CharTensor | torch.cuda.CharTensor
16-bit integer (signed) | torch.int16 or torch.short | torch.ShortTensor | torch.cuda.ShortTensor
32-bit integer (signed) | torch.int32 or torch.int | torch.IntTensor | torch.cuda.IntTensor
64-bit integer (signed) | torch.int64 or torch.long | torch.LongTensor | torch.cuda.LongTensor

### Creation from lists & numpy

In [15]:
z = torch.tensor([[1, 3], [2, 9]]).long()
print(z.type())
# Cast to numpy ndarray
z = z.numpy()
print(z)
print(z.dtype)

torch.LongTensor
[[1 3]
 [2 9]]
int64


In [16]:
# Data type inferred from numpy
print(torch.tensor(np.random.rand(5, 3)).type())
print(torch.tensor(np.random.rand(5, 3).astype(np.float32)).type())

torch.DoubleTensor
torch.FloatTensor


### Broadcasting

Basic operations on torch tensor or numpy array (addition, etc.) are done element by element, thus work on tensors of the same shape. Nevertheless, it’s possible to do operations on tensors of different shapes if torch can transform these tensors so that they all have the same shapes: this conversion is called **broadcasting**.

The image below gives an example of broadcasting:

![](http://www.scipy-lectures.org/_images/numpy_broadcasting.png)

In [17]:
a = torch.arange(0, 40, 10)
b = torch.arange(0, 3)
a = a.view(4,1) # a must be changed into a vertical array
print(a)
print(b)
print(a + b)

tensor([[ 0],
        [10],
        [20],
        [30]])
tensor([0, 1, 2])
tensor([[ 0,  1,  2],
        [10, 11, 12],
        [20, 21, 22],
        [30, 31, 32]])


In [18]:
a = np.arange(0, 40, 10)
b = np.arange(0, 3)
a = a.reshape((4,1)) 
print(a)
print(b)
print(a + b)

[[ 0]
 [10]
 [20]
 [30]]
[0 1 2]
[[ 0  1  2]
 [10 11 12]
 [20 21 22]
 [30 31 32]]


Adding scalar to tensor is also broadcasting!

In [19]:
p = torch.zeros(4, 4)
print(p)
print(p + 5)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor([[5., 5., 5., 5.],
        [5., 5., 5., 5.],
        [5., 5., 5., 5.],
        [5., 5., 5., 5.]])


### Reshape

In [20]:
y = torch.arange(0, 100)
print(y)
print(y.shape)
print(y.view(10, 10))
print(y.view(25, -1))

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
        36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53,
        54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71,
        72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89,
        90, 91, 92, 93, 94, 95, 96, 97, 98, 99])
torch.Size([100])
tensor([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
        [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
        [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
        [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])
tensor([[ 0,  1,  2,  3],
      

### Concatenate & Stack

In [21]:
# 1 is the dimension over which the tensors are concatenated
y = torch.randn(5, 5)
print(torch.cat([y, y], 1).size())
# stack concatenates the sequence of tensors along a new dimension.
print(torch.stack([y, y], 0).size())

torch.Size([5, 10])
torch.Size([2, 5, 5])


### Basic Slicing and Indexing

[numpy indexing](https://docs.scipy.org/doc/numpy-1.13.0/reference/arrays.indexing.html)

![](https://www.oreilly.com/library/view/python-for-data/9781449323592/httpatomoreillycomsourceoreillyimages1346882.png)

## Advanced Data Handling

### Advanced Slicing and Indexing

![](http://www.scipy-lectures.org/_images/numpy_indexing.png)

### Fancy Indexing
![](http://www.scipy-lectures.org/_images/numpy_fancy_indexing.png)